name: CI

on:
  pull_request:
    branches: ['*']

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Chrome binary
        run: chrome --version
        with:
          chrome-version: stable

      - name: Installling dependencies
        run: npm install

      - name: ESLint check
        run: npx eslint --ignore-path .gitignore .

      - name: Prettier check
        run: npx prettier --check --ignore-path .gitignore .

      - name: Test
        run: npm run test
        env:
          EXEC_PATH: google-chrome-stable

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
